### ISSUE TITLE
Spelling smh

### ISSUE THREAD

**Issue by Sierrawastaken** [ItsRichHeart/GuardianTechnicalResources#1]
Misspelled Guardian Lair as “Guardian Liar”.
Pls fix it breaks the pack. Also this doesnt make sense: “ meant as a collection for anyone to use and not something the members have build. “

oh god i cant keep reading this pls send help my eyes are dying

**Comment by trippsanders** [comment]
![image](https://user-images.githubusercontent.com/45514010/152651264-cc82f0de-a6b2-4415-8b60-d15a61b95e95.png)

**Comment by ItsRichHeart** [comment]
Fixed the spelling. If you have issues in the future, keep reporting them
